name: Planner
description: "Planner des modes de journée et des phases horaires"
version: "1.0.1"
slug: planner
init: false
arch:
  - amd64
  - armv7
  - aarch64
  - i386
startup: services
boot: auto
url: "https://github.com/jesuisla91/ha-addons"

# --- INTÉGRATION DANS HOME ASSISTANT ---
ingress: true
ingress_port: 8099
ingress_stream: false
panel_icon: mdi:calendar-clock
panel_title: Planner
panel_admin: false

# Plus de port exposé publiquement (plus de DuckDNS).
# Si tu veux malgré tout garder un accès direct pour debug, remets :
#   ports:
#     8099/tcp: 8099

map:
  - config:rw

options: {}
schema: {}
